groups/urls.py
from django.conf.urls import url
from . import views
app_name='groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(),name='all'),
    url(r'^new/$',views.CreateGroup.as_view(),name='create'),
    url(r'posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
    url(r'join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
      
    

]

mark1_pro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    url(r'accounts/',include('django.contrib.auth.urls')),
    url(r'^$', views.InPage.as_view(),name="in"),
    
    url(r'^$', views.OutPage.as_view(),name="out"),

    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    path('search',views.search,name='search'),
    path('search_group',views.search_group,name='search_group'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

posts/urls.py
from django.conf.urls import url

from . import views


app_name='posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
    url(r'^by/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment'),
    
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/like/$',views.LikePost,name='like'),
    url(r'^event/$',views.EventList.as_view(),name='event_all'),
    url(r'^lcc/$',views.LCCList.as_view(),name='lcc_all'),

    ]
    

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

import misaka

from django.contrib.auth import get_user_model

User = get_user_model()

from django import template
register =template.Library()

class Group(models.Model): #create model for selecting groups
    name=models.CharField(max_length=225,unique=True)
    slug= models.SlugField(allow_unicode=True,unique=True)
    description= models.TextField(blank=True,default='')
    description_html=models.TextField(editable=False,default='',blank=True)
    members=models.ManyToManyField(User,through='GroupMember',blank=True)
    
    def __str__(self):
        return self.name
    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        self.description_html=misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse ('groups:single',kwargs={'slug':self.slug})
    
    class Meta:
        ordering=['name']


class GroupMember(models.Model):
    group =models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user =models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.user.username

    class Meta:
        unique_together =('group','user')

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,PermissionRequiredMixin)
from django.contrib import messages
# Create your views here.

from django.urls import reverse
from django.views import generic
from groups.models import Group,GroupMember
from django.shortcuts import get_object_or_404
from . import models

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields=('name','description')
    model =Group

class SingleGroup(generic.DetailView):
    model=Group

class ListGroups(generic.ListView):
    model=Group


class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):

        group=get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        
        except :
            messages.warning(self.request,'Warning already a member!')
        else:
            messages.success(self.request,'You are henceforth a member')
            
        return super().get(request,*args,**kwargs)


class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    def get(self,request,*args,**kwargs):
        try:
            membership= models.GroupMember.objects.filter(
            user=self.request.user,
            group__slug=self.kwargs.get('slug') ).get() 

        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!')

        else:
            membership.delete()
            messages.success(self.request,'You left the group!') 

        return super().get(request,*args,**kwargs)

    

groups/templates/groups/group_base.html
{%extends "base.html" %}

{%block content%}

<div >
    
    <div class="row">
        {% block pregroup%}
        {%endblock%}
        {% block group_content%}
        {%endblock%}
        {% block postgroup%}
        {%endblock%}
  
  
    </div>
</div>
{%endblock%}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{%block pregroup%}


<h1>{{group.name}}</h1>

<h2>Member Count: {{group.members.count}}</h2>

{%if '@' in group.name.0 or '#' in group.name.0 or '*' in group.name.0%}
{% if user in group.members.all %}
<h3>Created by: @{{user.username}}</h3>
{%endif%}
{%endif%}
<div class="content">
    {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug%}" class='btn btn-lg btn-fill btn-warning'><span class='glyphicon glyphicon-remove-circle'></span> Leave</a>
    
    {%elif '@' in group.name.0 or '#' in group.name.0 or '*' in group.name.0 %}
     {%if group.members.count == 0%}
     <a href="{% url 'groups:join' slug=group.slug%}" class='btn btn-lg btn-fill btn-warning'><span class='glyphicon glyphicon-ok-circle'></span>Join</a>
     {%endif%}
     {% else %}
    <a href="{% url 'groups:join' slug=group.slug%}" class='btn btn-lg btn-fill btn-warning'><span class='glyphicon glyphicon-ok-circle'></span>Join</a>
    <h1>Hi there</h1>    
    
    {% endif %}

</div>
{%endblock%}


{%block group_content%}

<div class="col-md-8">
{% if group.posts.count == 0 %}
<h2>Be the first to ask your question!</h2>

{%else %}
{% if user in group.members.all or '@' in group.name.0 or '#' in group.name.0 or '*' in group.name.0%}
{% for post in group.posts.all%}
{%include "posts/_post.html"%}
{%endfor%}
{%endif%}
{%endif%}
</div>
{%endblock%}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}

{% load bootstrap3 %}


{% block group_content%}

<h1>Create a new Group</h1>

<form action="{% url 'groups:create'%}" method="post" id='groupForm'>
    {%csrf_token%}
    {%bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>

{%endblock%}

groups/templates/groups/group_list.html
{%extends "groups/group_base.html"%}
<link rel="stylesheet" href="master.css">


{%block pregroup%}

<div class="col-md-4">
    <div class="content">
        {%if user.is_authenticated%}
        <h2>Welcome Back!
        <a href="{%url 'posts:for_user' username=user.username%}">
            @{{user.username}}
        </h2>
       </a>
        {%endif%}
        <h2>Groups</h2>
        <p>Welcome to the group page</p>
        <form method="GET" action="/search_group" class="form-inline my-2 my-lg-0">
            <input type="Search" class="form-control mr-sm-2" placegolder="search_group" name='search_group' id="search_group" >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search Group</button>
        </form>
        
    </div>
    {%if user.is_authenticated%}
    <a href="{% url 'groups:create'%}" class='btn btn-md btn-fill btn warning'>
        <span class='glyphicon glyphicon-plus-sign'>CreateNewGroup!</span>
    </a>
    {%endif%}
 


{%endblock%}


{%block group_content%}
<style>
    .groupy{
        padding-left: 20%;
        width:1000px;
        background-color: rgb(247, 247, 247);

        
    }
    .list-group{
        padding-left:120%
    }
</style>
<div class="col-md-9">
    <div class="list-group">
        {%for group in object_list%}
        
        <a href="{% url 'groups:single' slug=group.slug%}">
           <div class="groupy"> 
            <h3 style="background-color: rgb(247, 245, 245); padding-left:25%">{{group.name}}</h3>
            
   
            
               <h3>{{group.description_html|safe}}</h3> 
                <div class="row">
                <div class="col-md-5">
                    <span class='badge'>{{group.members.count}}</span>
                    member{{group.members.count|pluralize}}
                </div>
                <div class="col-md-5">
                    <span class='badge'>{{group.posts.count}}</span>
                    post{{group.posts.count|pluralize}}

                </div>
            </div>
        </div>
        </a>
        {%endfor%}
    </div>
</div>
</div>

{%endblock%}