accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views #contains default view for login and logout


from . import views

app_name ='accounts' #app name for url


urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'), #url for login
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),#url for logout
    url(r'signup/$',views.Signup.as_view(),name='signup')#url for signup

]

mark1_pro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    url(r'accounts/',include('django.contrib.auth.urls')),
    url(r'^$', views.InPage.as_view(),name="in"),
    
    url(r'^$', views.OutPage.as_view(),name="out"),

    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    path('search',views.search,name='search'),
    path('search_group',views.search_group,name='search_group'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

posts/urls.py
from django.conf.urls import url

from . import views


app_name='posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
    url(r'^by/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment'),
    
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/like/$',views.LikePost,name='like'),
    url(r'^event/$',views.EventList.as_view(),name='event_all'),
    url(r'^lcc/$',views.LCCList.as_view(),name='lcc_all'),

    ]
    

templates/base.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/master.css' %}"> 
 
    <title>UniQ</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
     <link rel="stylesheet" href="{% static 'css/master.css' %}">
     <style>
        section
        {
            min-height: 1000px;
            width:100%;
        
          margin-top: auto;
          margin-bottom: auto;
          margin-left: auto;
          margin-right: auto;
          align-content: center;
        
        background-color: rgb(252, 252, 252);  
        
           }
        @keyframes change{
          0%
          {
            background-position:0 50%;
        
          }
          50%
          {
            background-position: 100% 50%;
        
          }
          100%
          {
              background-position: 0 50%;
          }
        
        }
        
        #Red,#Blue{
          visibility:visible;
          margin-left: 45%;
          margin-right: 30%;
          /* margin-right: 50%; */
          /* margin-bottom: 20vh; */
          margin-top: -15vh;
          font-size:5vh;
          /* text-align: center; */
          /* height: 20%; */
        
          color: red;
          position: relative;
        
          /* font-stretch: expanded; */
        
          /* margin-top: -860px; */
          /* padding: 3% 3%; */
        }
        
        
         #f1,#f2,#f3,#f4,#f5,#f6,#f7,#f8,#f9
        {
           width:30%;
          height:30%;
          /* color: #99d8ea; */
        }
        
        
        
      
        .body{
            padding:1.5%;
            border-style: solid;
        }
        div {
        
            background-color:rgb(252, 252, 252) ;   
       
          width:fit-content;
          padding-left: 0%;
          border-radius: 10px;
         
          

          
          
         
        }
        #h3{
            width:fit-content; 
        }
        

        p{
           
           
            background-color:  rgb(233, 233, 233);
            background-size:contain;
        
            border-color: black;
            border-width:0.5px;
            border-style:hidden;
            border-radius: 5px;
           
            
            width: fit-content;
           
           

        }
        
        .custcontent{
            border-style: solid ;

            border-color: white;

           width:fit-content
        }

        .container{
            border-style: solid;
            border-color: white;
          width:auto
           
        }
        .navbar-center{
            width:max-content;
        }

   

     



        
        
      
        </style>
        <link rel="stylesheet" href="master.css"> 

</head>

<body>
  <section>

  
    <nav class='navbar custnav navbar-fixed-top ' role='navigation' id='navbar'>

        <div class='container'>
          
            

            <ul  class='nav navbar-nav navbar-center' id="custnav" >

                {% if user.is_authenticated%}  <!-- if user is logged in-->
                <a class='navbar-brand custnav ' href="{% url 'home'%}"><h3 style="color: black;"><i><b>UniQ</b></i></h3></a>
              
                <li><a href="{%url 'posts:all'%}"><h3 style="color: black;"><i><b>Q&A</b></i></h3></a></li>
              
                <li><a href="{%url  'posts:event_all'%}"><h3 style="color: black;"><i><b>Event</b></i></h3></a></li>
                <li><a href="{%url 'posts:lcc_all'%}"><h3 style="color: black;"><i><b>Content</b></i></h3></a></li>
                <li><a href="{%url 'posts:create'%}"><h3 style="color: black;"><i><b>Post</b></i></h3></a></h4></li>
                <li><a href="{%url 'groups:all'%}"><h3 style="color: black;"><i><b>Groups</b></i></h3></a></li>
                <li><a href="{%url 'groups:create'%}"><h3 style="color: black;"><i><b>Create Group</b></i></h3></a></li>
               
                <li><a href="{%url 'posts:for_user' username=user.username%}"><h3 style="color: black;"><b><i>Profile</b></i></h3></a></li>
              
                <li><h1><form method="GET" action="/search" class="form-inline my-2 my-lg-0">
                  <input type="Search" class="form-control mr-sm-2" placegolder="search" name='search' id="search" ></>
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search Post</button>
              </form></h1> </li>

              <li><h1><form method="GET" action="/search_group" class="form-inline my-2 my-lg-0">
                <input type="Search" class="form-control mr-sm-2" placegolder="search_group" name='search_group' id="search_group" >
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search Group</button>
            </form></h1></li>
            <li><a href="{% url 'accounts:logout'%}"><h3 style="color: black;"><i><b>Log Out</b></i></h3></a></li>
               
          
                {%else%}
                <li><a href="{%url 'groups:all'%}"><h3 style="color: black;"><i><b>Groups</b></i></h3></a></li>
                <li><a href="{%url 'accounts:login'%}"><h3 style="color: black;"><i><b>Log In</b></i></h3></a></li>
                <li><a href="{% url 'accounts:signup'%}"><h3 style="color: black;"><i><b>Sign Up</b></i></h3></a></li>
               
                

                {% endif %}
                
            </ul>
             
        </div>
      
    </nav>
    <br>
    <br> 
    <br>
    <br>
   <br>
    
    

    <div class="container custcontent">
      
       <br>
        {%block content%}
       
        {%endblock%}
    </div>

</body>
</section>

</html>

templates/in.html
{%extends 'base.html'%}
{% block content%}


{%load static%}
<style>
    .column {
        float: left;
        width: 33.33%;
        padding: 5px;
      }
</style>

    

    <br>
<br>

<center>
    <h1>Welcome to UniQ</h1>
    <h1>What You get From this Website:</h1>
      
      <div class="row">
        <div class="column">
           <h1> <a href="{%url 'posts:all'%}">  <img width="300px" height="300px" src="static/pics/pic4.jfif" style="border-radius: 10px;"></a></h1>
        </div>
        
        <div class="column">
            <a href="{%url 'posts:lcc_all'%}">  <img width="300px" height="300px" src="static/pics/pic5.jfif" style="border-radius: 10px;"></a>
        </div>
        <div class="column">
          <h1>  <a href="{%url  'posts:event_all'%}"> <img width="300px" height="300px" src="static/pics/pic6.jfif" style="border-radius: 10px;"></a></h1>
        </div>
      </div>

       <h3><li>A Q&A forum regarding any University Topic</li></h3>
    <h3><li>A content creator forum where you can post your content and explore the works of other content creators</li></h3>
    <h3> <li>An Event Management forum where you can post about any workshops, tournaments,seminars etc</li></h3>
<br>
<br>
<br>
<br>
<br>

<h1>Group Conventions</h1>
<h3><li>An @ at start of group name will be an event Group</li></h3>

<h3><li>An # at start of group name will be a Content Creator Group</li></h3>
<h3><li>Any other group Name will represent a Q&A group</li></h3>
    <h1>Everybody is free to open a group</h1>
<br>
<br>
<br>
<h1>A Project By Team Tea Bag</h1>


</center>
   

{%endblock%}

templates/index.html
{%extends 'base.html'%}
{%block content%}
{%load static%}
<style>
    .column {
        float: left;
        width: 33.33%;
        padding: 5px;
      }
</style>

    

    <br>
<br>
{%if user.is_authenticated%}
<center>
    <h1>Welcome to UniQ</h1>
    <h1>What You get From this Website:</h1>
      
      <div class="row">
        <div class="column">
           <h1> <a href="{%url 'posts:all'%}">  <img width="300px" height="300px" src="static/pics/pic4.jfif" style="border-radius: 10px;"></a></h1>
        </div>
        
        <div class="column">
            <a href="{%url 'posts:lcc_all'%}">  <img width="300px" height="300px" src="static/pics/pic5.jfif" style="border-radius: 10px;"></a>
        </div>
        <div class="column">
          <h1>  <a href="{%url  'posts:event_all'%}"> <img width="300px" height="300px" src="static/pics/pic6.jfif" style="border-radius: 10px;"></a></h1>
        </div>
      </div>

       <h3><li>A Q&A forum regarding any University Topic</li></h3>
    <h3><li>A content creator forum where you can post your content and explore the works of other content creators</li></h3>
    <h3> <li>An Event Management forum where you can post about any workshops, tournaments,seminars etc</li></h3>
<br>
<br>
<br>
<br>
<br>

<h1>Group Conventions</h1>
<h3><li>An @ at start of group name will be an event Group</li></h3>

<h3><li>An # at start of group name will be a Content Creator Group</li></h3>
<h3><li>Any other group Name will represent a Q&A group</li></h3>
    <h1>Everybody is free to open a group</h1>
<br>
<br>
<br>
<h1>A Project By Team Tea Bag</h1>
{%else%}
<h1>Welcome to UniQ</h1>
    <h1>What You get From this Website:</h1>
      
      <div class="row">
        <div class="column">
           <h1>  <img width="300px" height="300px" src="static/pics/pic4.jfif" style="border-radius: 10px;"></h1>
        </div>
        
        <div class="column">
              <img width="300px" height="300px" src="static/pics/pic5.jfif" style="border-radius: 10px;">
        </div>
        <div class="column">
          <h1>   <img width="300px" height="300px" src="static/pics/pic6.jfif" style="border-radius: 10px;"></h1>
        </div>
      </div>

       <h3><li>A Q&A forum regarding any University Topic</li></h3>
    <h3><li>A content creator forum where you can post your content and explore the works of other content creators</li></h3>
    <h3> <li>An Event Management forum where you can post about any workshops, tournaments,seminars etc</li></h3>
<br>
<br>
<br>
<br>
<br>

<h1>Group Conventions</h1>
<h3><li>An @ at start of group name will be an event Group</li></h3>

<h3><li>An # at start of group name will be a Content Creator Group</li></h3>
<h3><li>Any other group Name will represent a Q&A group</li></h3>
    <h1>Everybody is free to open a group</h1>
<br>
<br>
<br>
<h1>A Project By Team Tea Bag</h1>

{%endif%}
</center>
   

{%endblock%}

templates/out.html
{%extends 'base.html'%}
{% block content%}

<h1>Logout test success</h1>

{%endblock%}

templates/search.html
{% extends "posts/post_base.html"%}



{%block post_content%}
<div class="col-md-8">
    
    
    
    {%for post in allPosts%}
    
    {% if user in post.group.members.all %}
      
    {%include "posts/_post.html"%}
  
    
    
    {%endif%}
   
  
   
    {%empty%}
    <h1>Post does not exist would you like to create one with this searchword?</h1>
    
   
    {%endfor%}
    
    
</div>

{%endblock%}

templates/search_group.html
{%extends "groups/group_base.html"%}

{%block pregroup%}

<div class="col-md-4">
    <div class="content">
        {%if user.is_authenticated%}
        <h2>Welcome Back!
        <a href="{%url 'posts:for_user' username=user.username%}">
            @{{user.username}}
        </h2>
       </a>
        {%endif%}
        <h2>Groups</h2>
        <p>Welcome to the group page</p>
        
        
    </div>
    {%if user.is_authenticated%}
    <a href="{% url 'groups:create'%}" class='btn btn-md btn-fill btn warning'>
        <span class='glyphicon glyphicon-plus-sign'>CreateNewGroup!</span>
    </a>
    {%endif%}
    <form method="GET" action="/search_group" class="form-inline my-2 my-lg-0">
        <input type="Search" class="form-control mr-sm-2" placegolder="search_group" name='search_group' id="search_group" >
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search Group</button>
    </form> 
</div>
{%endblock%}
{%block group_content%}
<style>
    .groupy{
        padding-left: 20%;
        width:1000px;
        background-color: rgb(247, 247, 247);

        
    }
    .list-group{
        padding-left:50%
    }
</style>
<div class="col-md-9">
    <div class="list-group">
        {%for group in allGroups%}
        <a href="{% url 'groups:single' slug=group.slug%}">
            <div class=groupy>
            <h3>{{group.name}}</h3>
            <div class="container-fluid">
                {{group.description_html|safe}}
                <div class="row">
                <div class="col-md-4">
                    <span class='badge'>{{group.members.count}}</span>
                    member{{group.members.count|pluralize}}
                </div>
                <div class="col-md-4">
                    <span class='badge'>{{group.posts.count}}</span>
                    post{{group.posts.count|pluralize}}
                </div>
                </div>
            </div>
        </div>
    
        </a>
        {%endfor%}
    </div>
</div>
{%endblock%}