mark1_pro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    url(r'accounts/',include('django.contrib.auth.urls')),
    url(r'^$', views.InPage.as_view(),name="in"),
    
    url(r'^$', views.OutPage.as_view(),name="out"),

    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    path('search',views.search,name='search'),
    path('search_group',views.search_group,name='search_group'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

posts/urls.py
from django.conf.urls import url

from . import views


app_name='posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
    url(r'^by/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment'),
    
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/like/$',views.LikePost,name='like'),
    url(r'^event/$',views.EventList.as_view(),name='event_all'),
    url(r'^lcc/$',views.LCCList.as_view(),name='lcc_all'),

    ]
    

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
import misaka
# Create your models here.
from groups.models import Group


from django.contrib.auth import get_user_model
User=get_user_model()
from ckeditor.fields import RichTextField
class Post(models.Model):
    user=models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_at= models.DateTimeField( auto_now=True)
    question=RichTextField(blank=True,null=True)
    #question=models.TextField()
    question_html=RichTextField(editable=False)
    group =models.ForeignKey(Group,related_name='posts',null=True,blank=False,on_delete=models.CASCADE)
    video=models.FileField(upload_to="video/%y",null=True,blank=True)
    image=models.FileField(null=True,blank=True)

    #caption=models.CharField(max_length=250,null=True,blank=True)
     
    
    def save(self,*args,**kwargs):
        self.question_html=misaka.html(self.question)
        
        super().save(*args,**kwargs)


    def get_absolute_url(self):
        return reverse("posts:single", kwargs={"pk": self.pk,'username':self.user.username})
    
    def approved_comments(self):
        return self.comments.filter(approved_comments=True)
    
    class Meta:
        ordering=['-created_at']
    def __str__(self):
        return self.question
    
    
class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    author=models.CharField(max_length=200)
    text=RichTextField(blank=True,null=True)
    created_date =models.DateTimeField(auto_now=True)
    approved_comment=models.BooleanField(default=False)
    likes=models.ManyToManyField(User,related_name='like_posts')    
    
    def approve(self):
        self.approved_comment=True
        self.save()

    def get_absolute_url(self):
        return reverse('posts:all')

    def total_likes(self):
        return self.likes.count()
    
    
    def __str__(self):
        return self.text

posts/forms.py
from posts.models import Post,Comment
from django import forms

class CommentForm(forms.ModelForm):

    class Meta():
        model=Comment
        fields=('author','text')

        widgets={
            'author':forms.TextInput(attrs= {'class':'textinput'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})

        }

posts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy,reverse
from posts.models import Post,Comment
from django.http import Http404,HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from braces.views import SelectRelatedMixin
from django.contrib.auth.decorators import login_required
from groups.models import Group

from .import models
from .import forms


from django.contrib.auth import get_user_model
from posts.forms import CommentForm

User=get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model=models.Post
    select_related=('user','group')

class UserPosts(generic.ListView):
    model=models.Post
    template_name ='posts/user_post_list.html'

    def  get_queryset(self):
        try:
            self.post_user =User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user 
             
       
        return context
       
class PostDetail(SelectRelatedMixin,generic.DetailView):
    model=models.Post
    select_related=('user','group')

    
    def  get_queryset(self):
        queryset=super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))
  

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields=('question','group','video','image')
    model=models.Post
    def form_valid(self,form):
        self.object= form.save(commit=False)
        self.object.user=self.request.user
        self.object.save()
        
        
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model=models.Post
    select_related=('user','group')
    success_url=reverse_lazy('home')
    def  get_queryset(self):
        queryset=super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)
        

@login_required
def add_comment_to_post(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect('posts:single',pk=post.pk,username=post.user.username)

    else:
        form=CommentForm()
    return render(request,'posts/comment_form.html',{'form':form})


@login_required
def comment_approve(request,pk):
    comment =get_object_or_404(Comment,pk=pk)
    comment.approve()
    post_pk=comment.post.pk
    return redirect('posts:single',pk=post_pk,username=comment.post.user.username)


@login_required
def comment_remove(request,pk):
    comment =get_object_or_404(Comment,pk=pk)
    post_pk=comment.post.pk
    comment.delete()
    return redirect('posts:single',pk=post_pk,username=comment.post.user.username)

@login_required
def LikePost(request,pk):
        comment=get_object_or_404(Comment,pk=pk)
        like=False
        print(like)
        if comment.likes.filter(id=request.user.id).exists():
            like=True
        else:
            like=False
        comment.likes.add(request.user)
        
        
        stuff=get_object_or_404(Comment,pk=pk)

        total_likes=stuff.total_likes()
       
        
        request.session['total_likes']=total_likes
        request.session['like']=like
        
        post_pk=comment.post.pk
        
        return redirect('posts:single',pk=post_pk,username=comment.post.user.username)


class EventList(SelectRelatedMixin,generic.ListView):
    model=models.Post
    select_related=('user','group')
    template_name ='posts/event_list.html'

class LCCList(SelectRelatedMixin,generic.ListView):
    model=models.Post
    select_related=('user','group')
    template_name ='posts/lcc_list.html'

posts/templates/posts/_post.html
{%load static%}



     <style>
        .outer{
            padding-left: 45%;
            padding-right: 0%;
            width:1400px;
            
          }
        .media-body{
            border-color: rgb(78, 78, 78);
            border-radius: 10px;
            border-width: 20px;
            border-style: solid;
            padding-left: 10%;
           border: rgb(78, 78, 78);
           
           background-color: rgb(233, 233, 233) ;
           
          }
          .post-media{
            border-color: rgb(139, 139, 139);
            border-radius: 10px;
            border-width: 5px;
            width:fit-content;
           padding-left:3%;
             padding-right:3%;
           
           background-color:  rgb(233, 233, 233)  ;
           
           border-style: solid;
           
          

        }

        .comtext{
            background-color: aliceblue;
        }
        .comtext2{
            background-color: aliceblue;
        }
        .comment{
            border-style:ridge;
            border-radius: 10px;
        }

        .size{
            width:min-content 
        }

     </style>

{%if post.user in post.group.members.all %}
<div class="outer">
    <br>
    <br>
<div class="post-media">
   
  
    <h3 id="size">{{post.question_html|safe}}</h3>
   

{%if post.video%}   
<video width="800" height="500" class ="video-fluid" controls >
<source src="{{post.video.url}}" type="video/mp4"/>
</video>
{%endif%}

{%if post.image%}
<img src="{{post.image.url}}" class="img-responsive"width="500" height="500" >
{%endif%}



<div class="media-body">
    {#<strong>{{post.user.username}}</strong>#}
    <h5 class='media-heading'>
    <span class='username'>
        <a href="{% url 'posts:for_user' username=post.user.username%}">@{{post.user.username}}</a>
    </span>
    <time class='time'>
             <a href="{% url 'posts:single' username=post.user.username pk=post.pk%}">
             {{post.created_at}}
         </a>
    </time>
    Group: <a href="{%url 'groups:single' slug=post.group.slug%}">{{post.group.name}}</a>    
</h5>

<div class="media-footer">
    
    {%if user.is_authenticated and post.user == user%}
    <a href="{% url 'posts:delete'  pk=post.pk%}" title="delete" class='btn btn-simple'>
        <span class='glyphicon glyphicon-remove text-danger' aria-hidden="true">

        </span>
        <span class='text-danger icon-label'>Delete</span>
    </a>
    {%endif%}

    
</div>

<div class="comment">

    <a class="btn btn-primary" href="{%url 'posts:add_comment' pk=post.pk%}">Answer</a>
    
    <h5>Answers:</h5>
    {%for comment in post.comments.all%}
    

    {%if user.is_authenticated or comment.approved_comment%}
    {{comment.created_date}}
    {%if not comment.approved_comment %}

    <a href="{% url 'posts:comment_remove'  pk=comment.pk %}" title="remove" class='btn btn-simple'>
        <span class='glyphicon glyphicon-remove text-danger' aria-hidden="true">

        </span>
        <span class='text-danger icon-label'>Remove</span>
    </a>
    
    <a href="{% url 'posts:comment_approve'  pk=comment.pk %}" title="approve" class='btn btn-simple'>
        <span class='glyphicon glyphicon-ok text-danger' aria-hidden="true">

        </span>
        <span class='text-danger icon-label'>Approve</span>
    </a>
   
    {%endif%}
    
    
    <h3>{{comment.text|safe|linebreaks}}</h3>
    <p class="comtext">Answered by:{{comment.author}}</p>
    
<form action="{% url 'posts:like' pk=comment.pk%}" method="POST">
    {%csrf_token%}
  
    <button type="submit", name="post_id",value="{{post.id}}",class="btn btn-primary btn-sm" style="background-color: rgb(172, 172, 255);">Vote</button>: {{comment.total_likes}}
</form>
    {%endif%}
    <br>    
    {%endfor%}
   

</div>
</div>


</div>
</div>

{%endif%}

posts/templates/posts/comment_form.html
{%extends "posts/post_base.html"%}

{% block content%}

<h1>New Answer</h1>

<form class="post-form" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.media}}
    {{form.as_p}}
    <button type="submit" class='save btn btn-default'>
        Post Answer
    </button>
</form>
{%endblock%}

posts/templates/posts/event_list.html
{% extends "posts/post_base.html"%}

{%block pre_post_content%}

<div class="col-md-4">

    {% if request.user.is_authenticated%}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class='title'>Your Groups</h5>
            <ul class='list-unstyled'>
                {%for member_group in get_user_groups%}
                <li class='group li-with-bullet'><a href="{% url 'groups:single' slug=member_group.group.slug%}"></a></li>
                {%endfor%}
            </ul>
        </div>
    </div>
    {%endif%}
  <div class="card card-with-shadow">
        <div class="content">
            <h5 class='title'>Your Groups</h5>
            <ul class='list-unstyled'>
                {%for other_group in get_other_groups%}
                <li class ='group li-with-bullet'>
                    <a href="{%url 'groups:single' slug=other_group.slug%}"></a>
                </li>
                {%endfor%}
            </ul>  
         </div>
    </div>
</div>
{%endblock%}


{%block post_content%}
<div class="col-md-8">
    {%for post in post_list%}
    {%if '@' in post.group.name.0 %}
    {%include "posts/_post.html"%}
    {%endif%}
    {%endfor%}
</div>

{%endblock%}

posts/templates/posts/lcc_list.html
{% extends "posts/post_base.html"%}

{%block pre_post_content%}

<div class="col-md-4">

    {% if request.user.is_authenticated%}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class='title'>Your Groups</h5>
            <ul class='list-unstyled'>
                {%for member_group in get_user_groups%}
                <li class='group li-with-bullet'><a href="{% url 'groups:single' slug=member_group.group.slug%}"></a></li>
                {%endfor%}
            </ul>
        </div>
    </div>
    {%endif%}
  <div class="card card-with-shadow">
        <div class="content">
            <h5 class='title'>Your Groups</h5>
            <ul class='list-unstyled'>
                {%for other_group in get_other_groups%}
                <li class ='group li-with-bullet'>
                    <a href="{%url 'groups:single' slug=other_group.slug%}"></a>
                </li>
                {%endfor%}
            </ul>  
         </div>
    </div>
</div>
{%endblock%}


{%block post_content%}
<div class="col-md-8">
    {%for post in post_list%}
    {%  if '#' in post.group.name.0 %}
   
   
    {%include "posts/_post.html"%}
    {%endif%}
    {%endfor%}
</div>

{%endblock%}

posts/templates/posts/post_base.html
{% extends "base.html" %}


{%block content%}

<div class="posts-page">
  
<div >
    
    <div class="row">
      
        {%block prepost%}
       
        {%endblock%}
        
        {%block post_content%}{%endblock%}
        
        {%block post_post%}{%endblock%}
    </div>

</div>
</div>

{%endblock%}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html"%}

{%block post_content%}

<h3>Are You sure?</h3>

<div class ="posts">
    {%include "posts/_post.html" with post=object hide_delete=True%}

</div>

<form method= "post">
    {%csrf_token%}
    <input type="submit" value="confirm delete" class="btn btn-danger btn-large">
    <a href="{%url 'posts:single' username=user.username pk=object.pk%}">   </a>
</form>

{%endblock%}

posts/templates/posts/post_detail.html
{%extends "posts/post_base.html"%}

{%block post_content%}


<div class="col-md-8"
>
{%if post.user in post.group.members.all %}
{%include "posts/_post.html"%}
</div>
{%else%}
<h1>To see your post please Join the group</h1>
{%endif%}
{%endblock%}

posts/templates/posts/post_form.html
{%extends "posts/post_base.html"%}
{%load bootstrap3%}
{%block post_content%}
<h4>Create New Post</h4>

<form action="{% url 'posts:create'%}" method="POST" id='postForm' enctype="multipart/form-data">
    {%csrf_token%}
    {{form.media}}
    {%bootstrap_form form%}
    
    <input type="submit" value="Post">
    
    
</form>











{%endblock%}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html"%}

{%block pre_post_content%}

<div class="col-md-4">

    {% if request.user.is_authenticated%}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class='title'>Your Groups</h5>
            <ul class='list-unstyled'>
                {%for member_group in get_user_groups%}
                <li class='group li-with-bullet'><a href="{% url 'groups:single' slug=member_group.group.slug%}"></a></li>
                {%endfor%}
            </ul>
        </div>
    </div>
    {%endif%}
  <div class="card card-with-shadow">
        <div class="content">
            <h5 class='title'>Your Groups</h5>
            <ul class='list-unstyled'>
                {%for other_group in get_other_groups%}
                <li class ='group li-with-bullet'>
                    <a href="{%url 'groups:single' slug=other_group.slug%}"></a>
                </li>
                {%endfor%}
            </ul>  
         </div>
    </div>
</div>
{%endblock%}


{%block post_content%}
<div class="col-md-8">
    <br>
    <br>
    {%for post in post_list%}
    {% if user in post.group.members.all and '@' not in post.group.name.0 and '#' not in post.group.name.0 %}
    
    {%include "posts/_post.html"%}
   
    
    {%endif%}
    {%endfor%}
</div>

{%endblock%}

posts/templates/posts/user_post_list.html
{%extends "posts/post_base.html"%}
{%load static%}
<link rel="stylesheet" href="{% static 'css/master.css' %}"> 
{%block prepost%}

<div class="col-md-5">
    <h1  style = "color:blue">@{{post_user.username}}</h1>
</div>

{%endblock%}

{%block post_content%}
<div class ="col-md-8">
    {%for post in post_list%}

    {%include "posts/_post.html"%}
    {%empty%}
    <center><h1>You have no post to show</h1></center>
   
    {%endfor%}

  
</div>

{%endblock%}

posts/templates/posts/video_form.html
<h1>Role problem</h1>